### ISSUE TITLE
Simple joint position control in joint stiffness mode

### ISSUE THREAD

**Issue by balakumar-s** [kuka-isir/rtt_lwr#8]
Thanks for writing great controllers. I am trying to implement a simple joint position controller using joint stiffness mode. I believe the problem is in the gains I set. The robot goes into a loud chatter when it is upright(0 angle position).  I need some help with these questions,
1. I see that you are using ros control to compute torques to control joint position. Was there a reason for not directly sending joint position to the joint impedance mode?  
2. Do you have the stiffness to be 1000 and damping to be 0.7 for all joints when sending joint torques?
3. Are you limiting the maximum change in torque or position when you send it to the robot?(The FRI does not do any threshold and directly applies the command to the joints).
Thanks.

**Comment by ahoarau** [comment]
If you are using rtt_lwr, then you could definitely try out this controller : https://github.com/kuka-isir/rtt_joint_traj_generator_kdl, it will give you clues on how everyting is connected.

1. We are just using ros_control for MoveIt because of the flexibility and the nice interface it provides, but most of Phd students use the very simple scheme of having one controller <--> LWR component <--> robot. 

We mostly use the robot as a pure torque interface because our research is around making optimisation based controllers that takes q,qdot as an input and computes the optimal torque T to track for the next millisecond. We could (and already did) control the robot in position using the controller inside the KRC, but we want to make our own.

2. We use the Joint impedance mode, but with stiffness and damping at 0.0 ! We want pure joint torque interface.

3. We are not. The robot stops if velocity is too high or effort is too important. If sending a very wong command, it'll try to go there but would break very rapidly. We also always have the red button in hand ;)

**Comment by balakumar-s** [comment]
Thanks for this information.
